// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQdLSzjogrMTMG6ifb0O9Utr_QnmFdn80',
    appId: '1:812857796899:web:ef645cfad3a51797420496',
    messagingSenderId: '812857796899',
    projectId: 'neqat-1707404182059',
    authDomain: 'neqat-1707404182059.firebaseapp.com',
    storageBucket: 'neqat-1707404182059.appspot.com',
    measurementId: 'G-563Z0WB99T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDro2PGsrxEeePoFhfAC9p2sht0fF0wY-w',
    appId: '1:812857796899:android:8ba3fc3113d480ad420496',
    messagingSenderId: '812857796899',
    projectId: 'neqat-1707404182059',
    storageBucket: 'neqat-1707404182059.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCys4LjRoimZrW0i3tgWj-efBxscBmlrYw',
    appId: '1:812857796899:ios:923dd0086ee0dd28420496',
    messagingSenderId: '812857796899',
    projectId: 'neqat-1707404182059',
    storageBucket: 'neqat-1707404182059.appspot.com',
    iosBundleId: 'com.example.neqatMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCys4LjRoimZrW0i3tgWj-efBxscBmlrYw',
    appId: '1:812857796899:ios:923dd0086ee0dd28420496',
    messagingSenderId: '812857796899',
    projectId: 'neqat-1707404182059',
    storageBucket: 'neqat-1707404182059.appspot.com',
    iosBundleId: 'com.example.neqatMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQdLSzjogrMTMG6ifb0O9Utr_QnmFdn80',
    appId: '1:812857796899:web:5143a029b49c54b4420496',
    messagingSenderId: '812857796899',
    projectId: 'neqat-1707404182059',
    authDomain: 'neqat-1707404182059.firebaseapp.com',
    storageBucket: 'neqat-1707404182059.appspot.com',
    measurementId: 'G-TS64G1XMD0',
  );
}
